// Auto-generated v0.1 ambient stubs for unresolved names from Mathub-platform imports.
// These are placeholders that let tsc pass; do NOT use at runtime — they will throw or no-op.
// Each name corresponds to a future integration point (Storage / LeanProvider / etc).
// To remove: implement the real provider + restore the proper import.
/* eslint-disable @typescript-eslint/no-explicit-any */

declare global {
  const AIModelId: any;
  type AIModelId = any;
  const CommitPageInput: any;
  type CommitPageInput = any;
  const DaemonClient: any;
  type DaemonClient = any;
  const Database: any;
  type Database = any;
  const JobContext: any;
  type JobContext = any;
  const JobManager: any;
  type JobManager = any;
  const PaperNodeInput: any;
  type PaperNodeInput = any;
  const RateLimitExceededError: any;
  type RateLimitExceededError = any;
  const SSEEvent: any;
  type SSEEvent = any;
  const SURVEY_MAX_CHARS: any;
  type SURVEY_MAX_CHARS = any;
  const SYSTEM_AGENT_USER_ID: any;
  type SYSTEM_AGENT_USER_ID = any;
  const SimilarProject: any;
  type SimilarProject = any;
  const TodoItem: any;
  type TodoItem = any;
  const UserSandboxManager: any;
  type UserSandboxManager = any;
  const addRelationTool: any;
  const addReviewCommentTool: any;
  const agentRuns: any;
  const agentScratchpads: any;
  const applyInitResult: any;
  const assistantGoalRuns: any;
  const assistantGoalSummaries: any;
  const assistantSkills: any;
  const assistantSubagentDeadEnds: any;
  const assistantSubagentRuns: any;
  const assistantTodos: any;
  const associatePaperToProject: any;
  const bookmarkPostTool: any;
  const botAccounts: any;
  const cancelScheduledTool: any;
  const channelMessages: any;
  const checkCodeSafety: any;
  const checkRateLimit: any;
  const computeNextPatrolAt: any;
  const conversations: any;
  const createDocPageTool: any;
  const createEffortTool: any;
  const createEffortVersionTool: any;
  const createForumPostTool: any;
  const createForumThreadTool: any;
  const createNotification: any;
  const createPollTool: any;
  const createReviewTool: any;
  const createWikiCommit: any;
  const createWikiPage: any;
  const createWikiPageTool: any;
  const crossProjectRelationsTool: any;
  const crossReferences: any;
  const deepResearchTool: any;
  const deleteDocPageTool: any;
  const deleteEffortTool: any;
  const deleteEffortVersionTool: any;
  const deleteForumPostTool: any;
  const deleteThreadTool: any;
  const drafts: any;
  const editThreadTitleTool: any;
  const escapeLike: any;
  const fetchArxivFullText: any;
  const flagPostTool: any;
  const forkEffortTool: any;
  const getDb: any;
  const getDocPageTool: any;
  const getPollTool: any;
  const getProgramIndexTool: any;
  const getProjectIndexTool: any;
  const getResearchProfileTool: any;
  const getReviewTool: any;
  const getScheduledTool: any;
  const getStructureTool: any;
  const getUserKnowledgeTool: any;
  const getUserPublicationsTool: any;
  const ingestCitation: any;
  const ingestPaper: any;
  const ingestSeedPapersForProject: any;
  const listBackrefsTool: any;
  const listDependentsTool: any;
  const listDocPagesTool: any;
  const listEffortIssuesTool: any;
  const listEffortVersionsTool: any;
  const listMentionsTool: any;
  const listProgramsTool: any;
  const listProjectThreadsTool: any;
  const listReviewsTool: any;
  const listThreadPostsTool: any;
  const listWikiPagesTool: any;
  const llmUsageLog: any;
  const log: any;
  const logSwallowed: any;
  const markAllThreadsReadTool: any;
  const markPostInsightfulTool: any;
  const markThreadReadTool: any;
  const movePostTool: any;
  const moveThreadToProjectTool: any;
  const moveThreadToStreamTool: any;
  const paperCitations: any;
  const paperNodes: any;
  const paperNodesTable: any;
  const postActivity: any;
  const posts: any;
  const programMembers: any;
  const programProjects: any;
  const programs: any;
  const projectMembers: any;
  const projectPapers: any;
  const projects: any;
  const queryDatabaseTool: any;
  const reactToPostTool: any;
  const readEffortDetailsTool: any;
  const readEffortGraphTool: any;
  const readEffortTool: any;
  const readProgramTool: any;
  const readThreadTool: any;
  const readWikiPageTool: any;
  const removeBookmarkTool: any;
  const removePostReactionTool: any;
  const removeRelationTool: any;
  const reorderDocPagesTool: any;
  const requestReviewTool: any;
  const requireRateLimit: any;
  const researchJournal: any;
  const researchMethodSkills: any;
  const researchStyle: any;
  const researcherProfiles: any;
  const resolveChildPath: any;
  const resolveReviewCommentTool: any;
  const safeFetch: any;
  const safeFetchBuffer: any;
  const schedulePostTool: any;
  const searchEffortsTool: any;
  const searchForumPostsTool: any;
  const searchForumTool: any;
  const searchGithubTool: any;
  const searchWikiTool: any;
  const setThreadLockedTool: any;
  const setThreadPinnedTool: any;
  const setThreadWatchTool: any;
  const slugify: any;
  const summarizeThreadTool: any;
  const threads: any;
  const updateDocPageTool: any;
  const updateEffortFormalStatementTool: any;
  const updateEffortFullTool: any;
  const updateEffortStatusTool: any;
  const updateEffortTool: any;
  const updateForumPostTool: any;
  const updateReviewTool: any;
  const updateStepStatus: any;
  const updateStructureTool: any;
  const updateThreadStatusTool: any;
  const updateWikiPage: any;
  const updateWikiPageTool: any;
  const users: any;
  const votePollTool: any;
  const wikiDrafts: any;
  const wikiPageVersions: any;
  const wikiPages: any;
  const wikiSyncQueue: any;
  const workspaceEffortFiles: any;
  const workspaceEfforts: any;
}

export {};
