#!/usr/bin/env node
/**
 * scripts/build-static-assets.ts
 *
 * Walks `dist/web/` (Vite output) and emits
 * `src/server/static-assets.generated.ts` — a TypeScript module that exports a
 * Map<string, EmbeddedAsset> of every file in the SPA build.
 *
 * The generated module is `import`ed by `src/server/static-assets.ts` and, via
 * that import, gets sucked into the single-binary by `bun build --compile`. At
 * runtime the compiled `mathran serve` can hand out the SPA without needing
 * `dist/web/` to exist next to the executable.
 *
 * Wire-up:
 *   scripts/build-binary.sh runs `vite build` (populates dist/web/), then
 *   `bun scripts/build-static-assets.ts`, then `bun build --compile ...`.
 *
 * The output file is gitignored — it's a build artifact, not source.
 *
 * Each asset is stored as a base64 string at module-eval time, then decoded
 * once into a `Uint8Array` via `Buffer.from(... , "base64")`. This keeps the
 * generated file `.ts`-clean and JSON-clean.
 */

import * as fs from "node:fs";
import * as path from "node:path";

const repoRoot = path.resolve(import.meta.dirname ?? path.dirname(new URL(import.meta.url).pathname), "..");
const webDir = path.join(repoRoot, "dist", "web");
const outFile = path.join(repoRoot, "src", "server", "static-assets.generated.ts");

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

function contentTypeFor(file: string): string {
  return CONTENT_TYPES[path.extname(file).toLowerCase()] ?? "application/octet-stream";
}

function walk(dir: string, out: string[] = []): string[] {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, ent.name);
    if (ent.isDirectory()) walk(full, out);
    else if (ent.isFile()) out.push(full);
  }
  return out;
}

function main(): void {
  if (!fs.existsSync(webDir)) {
    // Emit an empty Map so type-checking still works when the user hasn't run
    // `vite build` yet (e.g. clean clone running `tsc --noEmit`).
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(
      outFile,
      [
        "// AUTOGENERATED by scripts/build-static-assets.ts — do not edit.",
        "// dist/web/ was not present at generation time; the embedded asset",
        "// map is empty. Run `scripts/build-binary.sh` (or `vite build` first)",
        "// to populate it.",
        "",
        "import type { EmbeddedAssetRaw } from \"./static-assets.js\";",
        "",
        "export const EMBEDDED_ASSETS: ReadonlyArray<EmbeddedAssetRaw> = [];",
        "",
      ].join("\n"),
    );
    console.error(`[build-static-assets] dist/web missing — emitted empty manifest at ${outFile}`);
    return;
  }
  const files = walk(webDir).sort();
  const entries: string[] = [];
  let totalBytes = 0;
  for (const abs of files) {
    const rel = "/" + path.relative(webDir, abs).split(path.sep).join("/");
    const data = fs.readFileSync(abs);
    totalBytes += data.length;
    const base64 = data.toString("base64");
    const ct = contentTypeFor(abs);
    entries.push(
      `  { path: ${JSON.stringify(rel)}, contentType: ${JSON.stringify(ct)}, base64: ${JSON.stringify(base64)} },`,
    );
  }
  const body = [
    "// AUTOGENERATED by scripts/build-static-assets.ts — do not edit.",
    "// Source: dist/web/ (Vite build).",
    "//",
    `// Generated ${new Date().toISOString()} — ${files.length} file(s), ${totalBytes} byte(s) (pre-base64).`,
    "",
    "import type { EmbeddedAssetRaw } from \"./static-assets.js\";",
    "",
    "export const EMBEDDED_ASSETS: ReadonlyArray<EmbeddedAssetRaw> = [",
    entries.join("\n"),
    "];",
    "",
  ].join("\n");
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body);
  console.log(
    `[build-static-assets] wrote ${files.length} file(s) (${totalBytes} bytes) → ${path.relative(repoRoot, outFile)}`,
  );
}

main();
