/**
 * `mathran project init <name>` — scaffold a new project in the workspace.
 *
 * Creates the PRD §3b directory skeleton under
 * `<workspace>/projects/<slug>/`, writes `project.toml` metadata and
 * auto-generates a wiki home page (`wiki/index.md`).
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { fileURLToPath } from "node:url";
import { stringify as tomlStringify } from "smol-toml";
import { slugify } from "../../lib/slug.js";

export interface ProjectInitOptions {
  /** Explicit workspace root (highest precedence). */
  workspace?: string;
  /** Overwrite an existing project directory. */
  force?: boolean;
}

export interface ProjectInitResult {
  slug: string;
  projectDir: string;
  workspaceRoot: string;
}

/** Resolve the workspace root: --workspace flag > env > default `~/mathran-workspace`. */
export function resolveWorkspaceRoot(explicit?: string): string {
  if (explicit && explicit.length > 0) return path.resolve(explicit);
  const env = process.env.MATHRAN_WORKSPACE;
  if (env && env.length > 0) return path.resolve(env);
  return path.join(os.homedir(), "mathran-workspace");
}

async function readPackageVersion(): Promise<string> {
  try {
    const here = path.dirname(fileURLToPath(import.meta.url));
    // src/cli/commands -> repo root is three levels up.
    const pkgPath = path.resolve(here, "..", "..", "..", "package.json");
    const raw = await fs.readFile(pkgPath, "utf-8");
    const pkg = JSON.parse(raw);
    return typeof pkg.version === "string" ? pkg.version : "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function buildProjectToml(name: string, slug: string, createdAt: string, version: string): string {
  const data = {
    project: {
      name,
      slug,
      created_at: createdAt,
      mathran_version: version,
    },
    programs: {},
  };
  return tomlStringify(data) + "\n";
}

function buildWikiIndex(name: string, createdAt: string): string {
  return [
    "---",
    `title: ${name}`,
    "slug: index",
    `created_at: ${createdAt}`,
    "tags: [wiki, index]",
    "---",
    `# ${name}`,
    "",
    `Welcome to the wiki for **${name}**. This page was auto-generated by \`mathran project init\`.`,
    "",
  ].join("\n");
}

/**
 * Initialize a project. Returns the created paths.
 * Throws if the project already exists and `force` is not set.
 */
export async function initProject(name: string, opts: ProjectInitOptions = {}): Promise<ProjectInitResult> {
  const trimmed = name.trim();
  if (!trimmed) {
    throw new Error("project name must not be empty");
  }

  const workspaceRoot = resolveWorkspaceRoot(opts.workspace);
  const slug = slugify(trimmed);
  const projectDir = path.join(workspaceRoot, "projects", slug);

  let exists = false;
  try {
    await fs.access(projectDir);
    exists = true;
  } catch {
    exists = false;
  }
  if (exists && !opts.force) {
    throw new Error(`project already exists: ${projectDir} (use --force to overwrite)`);
  }
  if (exists && opts.force) {
    await fs.rm(projectDir, { recursive: true, force: true });
  }

  const createdAt = new Date().toISOString();
  const version = await readPackageVersion();

  // Directory skeleton (PRD §3b).
  await fs.mkdir(path.join(projectDir, "wiki"), { recursive: true });
  for (const dir of ["programs", "lean", "out"]) {
    await fs.mkdir(path.join(projectDir, dir), { recursive: true });
    await fs.writeFile(path.join(projectDir, dir, ".gitkeep"), "", "utf-8");
  }

  await fs.writeFile(path.join(projectDir, "project.toml"), buildProjectToml(trimmed, slug, createdAt, version), "utf-8");
  await fs.writeFile(path.join(projectDir, "wiki", "index.md"), buildWikiIndex(trimmed, createdAt), "utf-8");

  return { slug, projectDir, workspaceRoot };
}

/** CLI action handler. Returns a process exit code. */
export async function runProjectInit(name: string, opts: ProjectInitOptions): Promise<number> {
  try {
    const { slug, projectDir } = await initProject(name, opts);
    console.log(`mathran: created project '${slug}'`);
    console.log(`  ${projectDir}`);
    console.log("");
    console.log("Next steps:");
    console.log(`  mathran serve                 # browse this workspace`);
    console.log(`  mathran -p "..."             # run the agent in this project`);
    return 0;
  } catch (err: any) {
    console.error(`mathran project init: ${err?.message ?? err}`);
    return 1;
  }
}
