import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import { parse as tomlParse } from "smol-toml";
import { initProject, resolveWorkspaceRoot } from "./project.js";
import { slugify } from "../../lib/slug.js";

let tmpRoot: string;

beforeEach(async () => {
  tmpRoot = await fs.mkdtemp(path.join(os.tmpdir(), "mathran-proj-"));
});

afterEach(async () => {
  await fs.rm(tmpRoot, { recursive: true, force: true });
});

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

describe("slugify", () => {
  it("lowercases and replaces spaces", () => {
    expect(slugify("My Test Project")).toBe("my-test-project");
  });

  it("collapses duplicate and special chars and trims", () => {
    expect(slugify("  Foo!! @@ Bar__Baz  ")).toBe("foo-bar-baz");
  });

  it("falls back when input has no ascii alphanumerics", () => {
    expect(slugify("中文")).toBe("project");
    expect(slugify("中文", "untitled")).toBe("untitled");
  });

  it("keeps ascii subset from mixed names", () => {
    expect(slugify("数学 Algebra 2")).toBe("algebra-2");
  });
});

describe("resolveWorkspaceRoot", () => {
  it("prefers explicit over env", () => {
    process.env.MATHRAN_WORKSPACE = "/tmp/from-env";
    try {
      expect(resolveWorkspaceRoot("/tmp/explicit")).toBe(path.resolve("/tmp/explicit"));
    } finally {
      delete process.env.MATHRAN_WORKSPACE;
    }
  });

  it("uses env when no explicit", () => {
    process.env.MATHRAN_WORKSPACE = "/tmp/from-env";
    try {
      expect(resolveWorkspaceRoot()).toBe(path.resolve("/tmp/from-env"));
    } finally {
      delete process.env.MATHRAN_WORKSPACE;
    }
  });
});

describe("initProject", () => {
  it("creates the full directory skeleton", async () => {
    const { projectDir, slug } = await initProject("My Test Project", { workspace: tmpRoot });
    expect(slug).toBe("my-test-project");
    expect(projectDir).toBe(path.join(tmpRoot, "projects", "my-test-project"));

    expect(await exists(path.join(projectDir, "project.toml"))).toBe(true);
    expect(await exists(path.join(projectDir, "wiki", "index.md"))).toBe(true);
    for (const dir of ["programs", "lean", "out"]) {
      expect(await exists(path.join(projectDir, dir))).toBe(true);
      expect(await exists(path.join(projectDir, dir, ".gitkeep"))).toBe(true);
    }
  });

  it("writes a parseable project.toml with correct metadata", async () => {
    const { projectDir } = await initProject("My Test Project", { workspace: tmpRoot });
    const raw = await fs.readFile(path.join(projectDir, "project.toml"), "utf-8");
    const parsed: any = tomlParse(raw);
    expect(parsed.project.name).toBe("My Test Project");
    expect(parsed.project.slug).toBe("my-test-project");
    expect(typeof parsed.project.created_at).toBe("string");
    expect(typeof parsed.project.mathran_version).toBe("string");
    expect(parsed.programs).toBeDefined();
  });

  it("auto-generates wiki/index.md with front-matter and title", async () => {
    const { projectDir } = await initProject("My Test Project", { workspace: tmpRoot });
    const md = await fs.readFile(path.join(projectDir, "wiki", "index.md"), "utf-8");
    expect(md.startsWith("---\n")).toBe(true);
    expect(md).toContain("title: My Test Project");
    expect(md).toContain("slug: index");
    expect(md).toContain("tags: [wiki, index]");
    expect(md).toContain("# My Test Project");
    expect(md).toContain("auto-generated by `mathran project init`");
  });

  it("errors on duplicate init without --force", async () => {
    await initProject("Dup Project", { workspace: tmpRoot });
    await expect(initProject("Dup Project", { workspace: tmpRoot })).rejects.toThrow(/already exists/);
  });

  it("overwrites with --force", async () => {
    const { projectDir } = await initProject("Dup Project", { workspace: tmpRoot });
    const marker = path.join(projectDir, "wiki", "stale.md");
    await fs.writeFile(marker, "stale", "utf-8");
    expect(await exists(marker)).toBe(true);

    await initProject("Dup Project", { workspace: tmpRoot, force: true });
    expect(await exists(marker)).toBe(false);
    expect(await exists(path.join(projectDir, "project.toml"))).toBe(true);
  });

  it("rejects an empty name", async () => {
    await expect(initProject("   ", { workspace: tmpRoot })).rejects.toThrow(/must not be empty/);
  });

  it("handles special-character names via slug", async () => {
    const { slug, projectDir } = await initProject("Hello, World! (v2)", { workspace: tmpRoot });
    expect(slug).toBe("hello-world-v2");
    const parsed: any = tomlParse(await fs.readFile(path.join(projectDir, "project.toml"), "utf-8"));
    expect(parsed.project.name).toBe("Hello, World! (v2)");
    expect(parsed.project.slug).toBe("hello-world-v2");
  });
});
